### ISSUE TITLE
Rename reverse to rev?  concat* to append* ?

### ISSUE THREAD

**Issue by mars0i** [owlbarn/owl#109]
This is similar to #88.  I noticed that while Owl's function to reverse matrices is named `reverse`, while `Batteries.List`, `Batteries.Array`, `Core.List`, and the standard lib's `List` call the analogous functions `rev`.  (There doesn't seem to be a reverse function in `Core.Array` or the original standard lib `Array` module.  I haven't checked Containers.)

`reverse` is a clearer name, but maybe it would be worth following the model of the `List` and `Array` modules.  I'm not sure.

**Comment by mars0i** [comment]
Oh, also, you know this, but it's worth mentioning that Owl's `concat_horizontal`, `concat_vertical`, and `concatenate` are analogous to OCaml's `append` functions.  These names may have models elsewhere, though (e.g. Numpy?)

**Comment by ryanrhymes** [comment]
Thanks @mars0i , very useful comments. Yes `rev` seems more concise than `reverse`.  Actually, there are also some feedback about changing e.g. `equal` to `eq`; `less` to `lt`; `greater` to `gt`; and etc.

At the moment, I tend to use a bit longer and more self-explained naming scheme because Owl's core library need to accommodate much more functions than aforementioned standard libraries, having too many very short names may cause some confusion imo.

**Comment by mars0i** [comment]
Yes, I think there are tradeoffs.  I personally prefer something like `reverse`, in the abstract, except that I also like consistency between different libraries.
