### ISSUE TITLE
Module and directory naming

### ISSUE THREAD

**Issue by mor1** [owlbarn/owl#150]
It would be nice to sort out module naming / prefixing so that `(wrapped false)` was not necessary in the `src/owl/jbuild` stanza. (Or is there a particular reason not to do that?)

(It would seem more idiomatic to rename `src` to `lib` for a library such as Owl too.)

**Comment by ryanrhymes** [comment]
Originally I used `lib` then I changed to `src` since it seems more popular in many ocaml repo on github, maybe I am biased. Or is there any convention to follow?

For module naming, I think prefixing is a safe option in case the build system doesn't support the similar feature as that in jbuilder, also it helps in organising the hierarchy of the software, it often gives some hints about how the software is structured. I also tried `(wrapped true)` before, I remembered I encountered some issues in accessing some modules so I changed back. (but I cannot recall what issues honestly).

In ppl branch, I did some changes in reorganising the files by using different subfolders, then using `copy` rule while building, this seems a good solution atm before jbuilder supports subfolders.

**Comment by mor1** [comment]
The convention I think I've seen is `lib` for the source code for libraries, `src` (or `bin`) for the source code for executables. But it's not particularly tightly followed AFAICS.

Prefixing is a "safe" option but a bit ugly IMO. `(wrapped true)` ought to be possible to make work, though it may require some fiddling with module naming and possible with modules that include other modules? (I was assuming `(wrapped true)` used `pack` to put things into an archive but could be wrong, haven't checked.) I noticed this mostly in Actor actually-- the mixture of things like `Actor.Mapre` and `Actor_types` was confusing.

Not sure what you mean by jbuilder not supporting subfolders yet-- you mean in terms of mapping subfolders into submodules?

**Comment by ryanrhymes** [comment]
OK, I will have a look at Actor repo this weekend, having been distracted by Owl's work at the moment. For jbuilder, the files in the subdirectory need to be explicitly copied out while building, see  [https://github.com/ryanrhymes/owl/blob/master/src/owl/jbuild](https://github.com/ryanrhymes/owl/blob/master/src/owl/jbuild)
