### ISSUE TITLE
Changes in the function names for slicing

### ISSUE THREAD

**Issue by ryanrhymes** [owlbarn/owl#153]
The slicing functions have been reimplemented. My measurement shows the best case can lead to about 8 times improvement, you can check the performance measurement code in perftest folder.

However I am planning to make some changes to the existing APIs:
 
* change the original `get/set_slice` to `get/set_fancy`.

* change `get/set_slice_simple` to `get/set_slice`. 

The reason is really there are two sets of functions: 

* basic slicing functions are equivalent to those in numpy, it accepts slice definition which is a list of triplets defined by `[start;stop;step]`.

* fancy slicing functions are equivalent to the fancy indexing in numpy (to some extent) where you can pass in individual index, or a list of indices in any order. E.g., [R[2;5;1], L[2;2;1;5;3;4], I 6].

The following indexing operators will also be introduced (already in the ppl branch).

**.%{ }** for indexing, as follows.

```ocaml
open Arr;;

let x = sequential [|10; 10; 10|];;
let a = x.%{ [|2; 3; 4|] };;
x.%{ [|2; 3; 4|] } <- 111.;;
```

**.${ }** for basic slicing, as follows.

```ocaml
open Arr;;

let x = sequential [|10; 10; 10|];;
let a = x.${ [[0;4]; [6;-1]; [-1;0]] };;

let b = zeros (shape a);;
x.${ [[0;4]; [6;-1]; [-1;0]] } <- b;;
```

**.!{ }** for fancy slicing, as follows.

```ocaml
open Arr;;

let x = sequential [|10; 10; 10|];;
let a = x.!{ [ L[2;2;1]; R[6;-1]; I 5] };;

let b = zeros (shape a);;
x.!{ [L[2;2;1]; R[6;-1]; I 5] } <- b;;
```

So I hope the new naming can reflect the meaning of the function better. But you have different opinions, or if you have better naming schemes, please do let me know, many thanks!

**Comment by Octachron** [comment]
Have you thought about also using the new qualified extended indexing operators for these slice functions (e.g. `./[]`, `.%[]`)? One of the nice point of this new syntax is that it can be used in a qualified way
`x.Fancy.%[ indices ]` to avoid multiplying exotic syntaxes.

**Comment by ryanrhymes** [comment]
Thanks @Octachron yes, these new extended indexing operators will be used in the next release. 

I will also allocate one for indexing because after changing to `Genarray` completely, we cannot index a matrix with x.{i, j} any longer except using `get` and `set`.

**Comment by nilsbecker** [comment]
this looks like it's going to be a nice way to achieve concise slicing! i was wondering about the choice of indexing characters: according to the manual, other options include `@`, `=`, `|`, `:` etc. personally i find `$` nice since it evokes the word "slice". for indexing i would find `@` ("at") maybe more intuitive? if you come from python or matlab `:` may also be intuitive for slicing or fancy slicing. 

when looking at the expressions naively, it seems that `.${[ a; b; c]}` is redundant since there are directly nested brackets. however afaiu this is necessary since inside the curly brackets has to be a valid ocaml expression, and the only way to get a variable number of indices is by using a list. bummer.  For the special case of matrices however it should be possible to define slicing on a pair inside the brackets so that `.%{i, j}` or `.@{i, j}`  would work, correct?

**Comment by nilsbecker** [comment]
another thought: `{}` and `[]` and `()` are all available. maybe more than one of them could be used for easier disambiguation? for instance, indexing `.@[]` vs slicing `.@{}` ? with the same dot-ext character? 

just an idea -- maybe it's clearer do disambiguate via the dot-ext character. it just seemed that there is some extra syntactic space available that is not yet used.

**Comment by priamfive** [comment]
Would be good if simpler notation for special case of matrices were feasible as suggested by nilsbecker.

Sort of related: opening Mat (or Arr) as shown above to make compiler recognize x.%{}  etc, seems not a good idea as it causes other expressions not to be recognized (e.g. it objects to 2*2).

**Comment by nilsbecker** [comment]
addendum: the ocaml syntax support to enable more concise array indexing in owl has finally been merged. unfortunately, this will land only in 4.10 not in the upcoming 4.9 as that was already feature-frozen.
