### ISSUE TITLE
Slow dot product when picking columns from a matrix

### ISSUE THREAD

**Issue by jlouis** [owlbarn/owl#158]
The following code piece runs fast (on my machine):

```
open Owl
  
let _ =
  let x = Mat.uniform 1 1700 in
  let y = Mat.uniform 1700 1 in
  Mat.(x *@ y) |> Mat.print
```

However, if I create a matrix of shape [1700; 1700] and then pick two columns in that matrix, then the system looks like it loops infinitely (or takes a very long time. My agony-point was about 10 seconds :)

```
open Owl

let _ =
  let x = Mat.uniform 1700 1700 in
  let c1 = Mat.col x 77 in
  let c2 = Mat.(transpose (col x 75)) in
  Mat.(c1 *@ c2) |> Mat.print
```

I don't see why picking two columns, transposing one and running a dot product on them should take a long time. Granted, if the layout is row-major, then I'm not being nice to the cache, but it shouldn't take _that_ long time.

The computation I'm doing pits i,j columns to create an entry position i,j in a new matrix.

My current workaround is slow but works: I just loop through the two columns myself and runs the operations in OCaml. It is fine for the current prototype, but it wouldn't hold up in a more real setting I'm sure (the 1700 is quite arbitrary at the moment. The real world case is likely 45000 x 200_000 but so sparse that I can fill it out with a couple of hash tables rather than blindly doing matmul/dotprods).

Environment: Ocaml 4.05.0, Owl 0.3.0 from OPAM, hand built openblas from a couple of days ago.

I wanted to try 4.06.0 and owl from github, but it needed a bit more work since my application includes core, async, async_extended and the latter pulls in re2. re2 couldn't currently compile when I tried. However, I can try a 4.06.0 installation as well if you can't reproduce on your end. It just takes a bit more time.

**Comment by ryanrhymes** [comment]
Hi Jesper, thanks for reporting this. The slowness is due to the `Mat.print` function actually. 

The reason is `print` tries to pretty print all the elements in the matrix, Owl needs to traverse through all the elements more than once to calculate the width and other information. Because print function also accepts higher-order format function passed in to convert element to string, that makes it even slower.

If you don't need to print out all the elements, you can use ``Arr.pp_dsnda`` for the time being, it pretty prints a summary of the element, much faster. I haven't really spent much time in writing print functions for Owl but have been focusing on numerical functions. But I can find some time in optimising the printing function in ``Owl_pretty.ml``.

Thanks again for telling me about this issue, let me know if removing that ``print`` speed up your calculation? Besides, I recommend using master branch since it stays most up-to-date.

**Comment by jlouis** [comment]
There is still a thing I don't understand with the times it takes to do operations. Consider the following program:

```
open Owl

let _ =
  let x = Mat.uniform 1 1700 in
  let y = Mat.uniform 1700 1 in
  let t1 = Utils.time (fun () -> Mat.(x *@ y)) in
  let x = Mat.uniform 1700 1700 in
  let c1 = Mat.col x 77 in
  let c2 = Mat.(transpose (col x 75)) in
  let t2 = Utils.time (fun () -> Mat.(c1 *@ c2)) in
  Printf.printf "T1: %e, T2: %e\n" t1 t2
```

When I run it on my machine (Macbook Pro, 15 inch, 2017, 2.8 Ghz Core i7) I obtain the following result:

```
Jespers-MacBook-Pro:test jesperlouisandersen$ ./_build/default/owl_test.exe
T1: 6.699562e-02, T2: 1.441002e+01
```

Multiple runs agrees roughly with this. Why is the second method orders of magnitude slower than the first one? I would have expected that obtaining a column of a matrix, transposing one side and then running a dotprod would be closer in speed. In short: what am I seeing here?

I did try running the github `master` on 4.05.0 (it requires a couple of patches to remove some convenience functions so it works with 4.05.0, but I don't remember that it ran differently). I'll see if I can coerce the `re2` library to build on my 4.06.0 switch, so I can move to the tip of the github variant (and pin it while I'm here).

**Comment by ryanrhymes** [comment]
Hi, because in the first method you get an `1 x 1` matrix as result, whereas you a `1700 x 1700` matrix.

**Comment by jlouis** [comment]
Ah! Thank you! I'm treating rows for columns and columns for rows. Flipping c2 and c1 obtains the correct expected runtime (and the right shape of the output matrix to boot)
