### ISSUE TITLE
owl.opam: ocaml-version >= 4.06.0 ?!

### ISSUE THREAD

**Issue by UnixJunkie** [owlbarn/owl#174]
Owl is a very useful library, supporting a wider range of OCaml versions would be much welcome.

**Comment by igarnier** [comment]
I believe 4.06 is required for the custom indexing and slicing operators. If they are used internally by Owl it will be tough to make Owl compatible with OCaml < 4.06

**Comment by mars0i** [comment]
@UnixJunkie I think this is a reasonable concern.  It is a drawback that the current version requires 4.06 for the reasons that @igarnier stated, I believe.  Owl is a great tool that is very mature in many ways, but the < 1.0 version designation nevertheless has real meaning in this case.  Liang and others are trying to develop a rational, elegant, efficient, and useful system I believe, and there are still breaking changes happening as tradeoffs are negotiated.  Given that, I think it's reasonable for Owl to depend on new functionality from the most recent OCaml version that turns out to be potentially very useful for Owl.  I assume that the system will stabilize in the end, and by that point it will probably be able to support several future OCaml versions.  Just my thoughts off the top of my head.

**Comment by UnixJunkie** [comment]
'custom indexing and slicing operators'... I have no idea of what it is.
But I don't know any syntactic sugar that cannot be replaced by a simple function, portable across most OCaml versions.

**Comment by igarnier** [comment]
Sure :)
Actually, the only place where I can find them is in this file: https://github.com/ryanrhymes/owl/blob/master/src/base/misc/owl_operator.ml (for instance,  `let ( .%{ } ) x i = M.get x i.(0) i.(1)`)
So it should be possible to conditionally compile them with eg https://github.com/janestreet/ppx_optcomp

**Comment by ryanrhymes** [comment]
Thank you guys for the discussion here. Yes, I recently set the version constraint to 4.06.0 in order to use the extended indexing operators. There are several functions using the extended indexing operators at the moment:

- `get_slice`
- `set_slice`
- `get_fancy`
- `set_fancy`
- `Matrix/Ndarray.get`
- `Matrix/Ndarray.set`

You can find all these associated operators in [ [this doc] ](http://www.cl.cam.ac.uk/~lw525/owl/apidoc/owl_operator.html)

I acknowledge that I had quite some concerns when setting that constraint. But these operators can indeed help us in writing very concise code that easy to understand. This attractiveness is hard to resist :)

This is not something unsolvable imo. Conditional compilation is definitely one way to go. I am not very familiar with ppx_optcomp, but I can certainly have a look later next week and see how to address this. Thanks @igarnier for this ref, also thank you @UnixJunkie @mars0i for the pointing out this issue and good words.
