### ISSUE TITLE
Current status of GPU support?

### ISSUE THREAD

**Issue by doofin** [owlbarn/owl#185]

**Comment by cfhammill** [comment]
The opencl module looks pretty great. @ryanrhymes what steps are needed for algodiff of the opencl ndarrays?

**Comment by ryanrhymes** [comment]
The basic functionality to connect OCaml's bigarray and OpenCL, and executing basic vectorised maths have been implemented (actually a long time ago last year). You can even mix raw opencl code dynamically in OCaml code.

The current missing bits are: First, the layer between OpenCL module and Core module (in order to run Algodiff and others) is missing, this requires some design and experiment. Second, many opencl kernels for useful math functions are missing (e.g. dot product). I either write them myself or to see if I can find any available one that I can include.

For CUDA, I have plan to support. The concern is that it ties to one specific vendor, and I don't know how many have a NVIDIA card ... e.g. I myself don't have one and this also has been blocking me from trying CUDA related stuff.

Overall, I am planning to incorporate a more complete and mature GPU support by the end of this year.

**Comment by mars0i** [comment]
fwiw, I just learned that the computing cluster here at my university uses NVIDIA and CUDA.  They apparently have a lot of NVIDIA cores.  I'm mentioning this just as an additional data point.  Personally, I probably won't benefit from GPU support--not with my current project, anyway.
