### ISSUE TITLE
Bug in normalisation neuron?

### ISSUE THREAD

**Issue by ryanrhymes** [owlbarn/owl#225]
@jzstark With the recent PR #224 , the `example/cifar10_vgg.ml` is broken. Can you investigate this issue further to make sure that the normalisation neuron is really correct.

**Comment by ryanrhymes** [comment]
@jzstark If I change the learning rate from Adagrad 0.005 to Adagrad 0.001, it does not return `nan` any more, but the training does not seem to converge.

**Comment by jzstark** [comment]
Thanks! About using division instead multiplication --  I was trying to use multiplication at first, but then the `nan` problem was still there. I think maybe it's because by flipping the numerator and denominator, the calculate `a` would become quite small (`1 / (100 * 32 * 32) = 9.8E-6` in CIFAR example's case) so there is the float number precision issue.
