### ISSUE TITLE
add "append" option to save_txt

### ISSUE THREAD

**Issue by ghennequin** [owlbarn/owl#261]
Would it be possible add an "append" option (default to false) to `save_txt`; intended behaviour: if `append=true`, then write the matrix at the end of the file, leaving what's currently in the file unaffected. This would greatly simplify some of our simulations where we periodically save e.g. momentary performance of an interative algorithm into a file for online monitoring. Right now we have to maintain a history (list bookkeeping etc) where we could simply "append" to the file. Thanks!

**Comment by mars0i** [comment]
This seems like a good idea to me.  `save_txt` formats the output as it writes, so as it's written now, there's no straightforward way to extract the formatting from the file writing to allow appending with some more generic file writing code.  `save_txt` could be rewritten so that formatting the text is performed in a separate function, and then you could write it on your own.  But this seems inconvenience.  Moreover, I think that modifying `save_txt` to allow appending would mainly involve replacing [`let h = open_out f in`](https://github.com/owlbarn/owl/blob/37038239b530ce3dc280f12c1adaf9775d59ba9e/src/owl/dense/owl_dense_matrix_generic.ml#L563) with something like

    let h = open_out_gen [Open_rdonly; Open_creat; Open_append] 0o644 f

The list of flags could be built as either `[Open_rdonly; Open_creat; Open_append]` or `[Open_rdonly; Open_creat; Open_trunc]` depending on whether the option is passed.

(It looks like the file create permission gets ANDed with the user's own permission mask, so it seems OK to hardcode it into the `open_output_gen` call.)

@ryanrhymes, if you think this is a good idea, I would be happy to submit a PR if you want.

**Comment by ghennequin** [comment]
Hi mars0i, this sounds like a good idea to me!

**Comment by mars0i** [comment]
It's not a lot of work. I'll try to create a PR some time this week, and see what others think then.  It's really easier to have inside Owl rather than writing it oneself externally.

**Comment by ryanrhymes** [comment]
Thank you Marshall for implementing this feature 💯

**Comment by ghennequin** [comment]
thanks @mars0i !
