### ISSUE TITLE
auto-backward slicing

### ISSUE THREAD

**Issue by nilsbecker** [owlbarn/owl#28]
on the slicing tutorial i saw that `[3;1]` will be expanded into `[3;1;-1]`. while i like  the other slicing rules, i doubt that this particular automatic backward slicing expansion is a good idea. 

reason: it's often useful in algorithms to have backwards ranges yield an empty result. for example, if the first slice bound is a running variable `[i; fixed]` then as soon as `i` exceeds `fixed`, we get an empty return which is often what is needed. in contrast, iterating backwards over an array is more rare in my experience, and if it is desired, it does not hurt to be forced to explicitly give the `-1` as a step in these cases. (fwiw, numpy gives empty as well) 

[edit]: after trying the slicing functions out, i still think it would be feasible to return a matrix with shape 0 in all dimensions where the given range specification goes backwards without an explicit negative increment. admittedly, such matrices are normally not useful on their own, but could be useful corner cases in algorithms. e.g. iterating over the 0 dimension does nothing, folding gives the initial value, etc.

**Comment by ryanrhymes** [comment]
OK, i see. I think it is really about who should check the boundary and what should be the default behaviour when starting index is greater than ending index, without stepping size specified. 

imo, it should be developer's task to check the boundary in this case. Because if an algorithm can stop by detecting an empty return, why it cannot detect that the starting index is already beyond the boundary? 

I don't know anyone else has comment on this, but I would love to know.

**Comment by nilsbecker** [comment]
i agree that it could be checked explicitly. 

what i had in mind was e.g. something like this: make a list of `slice [[f i; g i]] somearray` for some range of indices `i` and some arbitraty `int->int` functions `f` and `g`. then stack all of the arrays in the list with `Mat.concat_vertical` -- if backwards slicing returns empty rows, then they just disappear in the stacking. 
for reference, a discussion in lacaml about empty array dimensions: https://github.com/mmottl/lacaml/issues/22
