### ISSUE TITLE
[feature request] latex labels for piloting and ODE solvers

### ISSUE THREAD

**Issue by AlexanderKoshkarov** [owlbarn/owl#38]
Wow, that looks awesome. 
This library makes me want to try ocaml  instead of my current julia workflow because I miss ML/OCaml/haskell. 
I have a feature request :) It looks like ploting part cannot generate latex style labels and titles. It would be nice to have.

and I have a question. would owl arrays work with Sundials/ML http://inria-parkas.github.io/sundialsml/ ? if not, maybe there it would be nice to have a wraper of ODE solver in owl from gsl or sundials :)

**Comment by ryanrhymes** [comment]
Hi @AlexanderKoshkarov, thanks for trying out Owl.

> I have a feature request :) It looks like ploting part cannot generate latex style labels and titles. It would be nice to have.

The plotting function is built atop of Plplot. Plplot supports postscript driver but I am not sure whether it supports latex math format actually. @hcarty knows better than I do, so maybe he can answer :)

> and I have a question. would owl arrays work with Sundials/ML http://inria-parkas.github.io/sundialsml/ ? if not, maybe there it would be nice to have a wraper of ODE solver in owl from gsl or sundials :)

At the moment, there is no ODE module in Owl. I may consider to add one module in future just for convenience, but I don't intend to compete with other specialised libs. Sundialsml seems a good option for ODE. I tried a bit a moment ago, to answer your question.

For `Sundials.RealArray2.t`, it is very easy since it is just `float64` Bigarray.Array2.t  You simply use `wrap` and `unwrap` functions in `Sundials.RealArray2` as below

```ocaml
let x = Sundials.RealArray2.make 5 5 1.;;
let y = Sundials.RealArray2.unwrap x;;

let z = Owl.Mat.tile y [|2;2|];;
let z = Sundials.RealArray2.wrap z;;
```

Note `wrap` and `unwrap` doesn't create extra copies so very efficient. 

For `Sundials.RealArray.t`, it is interesting because it is also just Bigarray.Array1.t so Owl should be able to handle it. But unlike `Sundials.RealArray2`, there is not `wrap` and `unwrap` function in this module and `Sundials.RealArray.t` seems wrapped into abstract type. So in order to pass it into Owl, you need to convert using float arrays (if you don't want to use obj (black) magic). E.g.,

```ocaml
let x = Sundials.RealArray.make 5 1.;;
let y = Mat.of_array (Sundials.RealArray.to_array x) 1 5;;
...
```

I think currently the best way is using Owl for more complicated matrix operations then using Sundials for ODE, these two should be able to work together without any problem imo.

**Comment by hcarty** [comment]
Plplot does not have any special latex labeling support to my knowledge.

**Comment by tbrk** [comment]
Hello @ryanrhymes and @AlexanderKoshkarov. This does look like a cool library. A few details about arrays and nvectors in Sundials/ML:
* As you say, `Sundials.RealArray2.unwrap` is efficient (`=fst`), but `Sundials.RealArray2.wrap` has a cost as it must generate a column pointer array (https://github.com/inria-parkas/sundialsml/blob/2.7.0-release/src/sundials/sundials_ml.c#L110).
* `Sundials.RealArray.t` is just a synonym for a `BigArray` (https://github.com/inria-parkas/sundialsml/blob/2.7.0-release/src/sundials/sundials.mli#L97), so no conversions are needed.
* `Nvectors` also include `wrap` and `unwrap` functions from and to `BigArray`s (e.g., https://github.com/inria-parkas/sundialsml/blob/2.7.0-release/src/nvectors/nvector_serial.mli#L39). Again, `unwrap` is almost for free and `wrap` is more expensive.
* In any case, you can continue to access an array after wrapping it. The underlying data is shared.
* Sundials/ML also interfaces the `Dls` (dense and banded) `Sls` (sparse) matrix data structures sometimes used within Sundials. Interoperability with these may be trickier.

It should definitely be possible to use Owl in callbacks from Sundials/ML. Any suggestions are welcome. I don't think we have a lot of users, so it should still be possible to improve the API if necessary.

**Comment by mars0i** [comment]
Just to add a little further confirmation to what hcarty wrote about LaTeX strings, I noticed that the documentation for `plmtex` or `and `plmtex3`, two label-writing functions, doesn't mention LaTeX despite what's suggested by their names.  Just to be sure I tried inserting some LaTeX into a string passed to `plmtex` and found, as expected, that it was printed as is.  "tex" in the names is apparently just an abbreviation for "text".
