### ISSUE TITLE
how to pass -L/usr/local/lib to find openblas

### ISSUE THREAD

**Issue by tenomoto** [owlbarn/owl#433]
I am trying to build Owl on FreeBSD, but fails to find openblas.
openblas is installed in the standard location i.e. `/usr/local/lib`.
I have `LDFLAGS=-L/usr/local/lib` set, but dune does not seem to respect it.
I haven't figured out how to set build settings with dune.

I tried to edit `.opam/4.08.1/.opam-switch/build/owl.0.6.0/src/owl/config/configure.ml`, but it seems to be generated at build time.

**Comment by mseri** [comment]
If `pkgconfig` is configured appropriately, then https://github.com/owlbarn/owl/blob/master/src/owl/config/configure.ml#L190 should use the correct flags, otherwise we attempt to use these defaults: https://github.com/owlbarn/owl/blob/master/src/owl/config/configure.ml#L126

We could change the code to add the additional path to the defaults checked, use the value from an env variable, say `OWL_OPENBLAS_LDFLAGS`, or add support for `OWL_LDFLAGS` to the build configuration file (something like https://github.com/owlbarn/owl/blob/master/src/owl/config/configure.ml#L76).

To test your changes you can clone the repository locally, commit the changes and `opam pin owl PATH_TO_YOUR_CLONE`. I would be happy to review your PR if you manage to fix it.

**Comment by tenomoto** [comment]
Thanks! Providing `openblas.pc` worked fine. Created a [gist](https://gist.github.com/tenomoto/cc9c721fc12c21e84c17503f41d6d868).
