### ISSUE TITLE
Scalar power operators?

### ISSUE THREAD

**Issue by mars0i** [owlbarn/owl#46]
I'm not sure if this should be a new issue.  It's closely related to #21.

I was experimenting with the 3D plotting examples in Tutorial 4.  That page still uses the old operator system, but that’s just a temporary problem.

The first 3D example includes this expression:
`let z0 = Mat.(sin ((x **@ 2.) +@ (y **@ 2.))) in`
`+@` is now `+` in `Mat`.  I think that `**@` refers to the function now called `pow1`, which raises each element of a matrix to a scalar power, but I don’t think that `pow1` or `pow0` (similar, but with arguments in the other order) are assigned to operators in `Mat` now.  This might be intended, but I thought I'd mention it in case it's an oversight.

**Comment by ryanrhymes** [comment]
Thanks for pointing it out. I have fixed the Plot tutorial. There are also some adjustments made to the APIs. pow0 and pow1 are now changed to pow_scalar and scalar_pow, you can use **$ and $** correspondingly. Of course if you Ext module, then you always use `**` and not need to worry about which is scalar and which is matrix.

The reason I didn't assign any operators to pow0 and pow1 before is because their naming need to be changed to be consistent with other operations in Owl (e.g. scalar_add and add_scalar). Thanks again for pointing it out.
