### ISSUE TITLE
stochastic test failures of algodiff reverse matrix.040 [sylvester.] and discrete_lyapunov

### ISSUE THREAD

**Issue by bcdarwin** [owlbarn/owl#460]
building against nixpkgs dependencies according to https://github.com/NixOS/nixpkgs/pull/74274 .

**Comment by ryanrhymes** [comment]
Calvin @tachukao is actually investigating this issue at the moment. It might be numerical stability issue because most of the time it passes on our machines.

Calvin checked `Linalg.trsyl` function it relies on, it turns out that Owl has correctly implemented trsyl whereas Scipy's seems buggy, he is preparing a pull req to scipy ;)

For this issue, the investigation is ongoing, @tachukao can comment more in case I miss anything or misunderstood anything.

**Comment by tachukao** [comment]
@bcdarwin  currently we are testing the reverse mode gradients by comparing them with finite difference approximations of these gradients, which are prone to numerical errors.
I'm still unsure whether these tests are failing due to numerical errors in the finite difference approximations or from the calculations of reverse mode gradients. As @ryanrhymes mentioned, the investigation is ongoing...

**Comment by mseri** [comment]
Hopefully this is fixed by #467

**Comment by mseri** [comment]
@bcdarwin can you check if it fixed the issue for you?

**Comment by bcdarwin** [comment]
Seems to be passing reliably now!

**Comment by mseri** [comment]
I will draft a new release of owl before next week
