### ISSUE TITLE
Owl will not be compatible with the next version of ctypes

### ISSUE THREAD

**Issue by mseri** [owlbarn/owl#489]
See https://github.com/ocaml/opam-repository/pull/15708

**Comment by yallop** [comment]
I hadn't spotted that this change would affect `owl`.

The goal of the change in `ctypes` (https://github.com/ocamllabs/ocaml-ctypes/commit/a900b59ef487d0c0f5feca5b607ef252d19af683) is to track the allocation status of some objects in the types of the OCaml values that reference them.  The change is essentially internal, but it does change the interface between the code generated by `ctypes` and the `ctypes` library (i.e. the [`Cstubs_internals`](https://github.com/ocamllabs/ocaml-ctypes/blob/a900b59ef487d0c0f5feca5b607ef252d19af683/src/ctypes/cstubs_internals.mli) interface).  Since `owl` generates code directly rather than using the `ctypes` generator, it's also affected.

The main change should be to replace
```ocaml
... cptr p ...
```

with
```ocaml
let Cpointer x = p in ... x ...
```

i.e. to use a `let` binding to unpack pointers rather than the `cptr` function.  I'm happy to help with getting `owl` working with the new interface, if it would be useful.

If this is going to cause major problems, please let me know and we can reconsider.

**Comment by mseri** [comment]
Thanks! I think it will be fine. In case we hit some rough edge we will ping for help

**Comment by tachukao** [comment]
we can probably close this now?!
