### ISSUE TITLE
Unable to save a neural network

### ISSUE THREAD

**Issue by jzstark** [owlbarn/owl#92]
I was trying to save a network using the code below (from `example/mnist_cnn.ml`):

```ocaml
open Owl
open Neural.S
open Neural.S.Graph
open Algodiff.S

let make_network input_shape =
  input input_shape
  |> lambda (fun x -> Maths.(x / F 256.))
  |> conv2d [|5;5;1;32|] [|1;1|] ~act_typ:Activation.Relu
  |> max_pool2d [|2;2|] [|2;2|]
  |> dropout 0.1
  |> fully_connected 1024 ~act_typ:Activation.Relu
  |> linear 10 ~act_typ:Activation.Softmax
  |> get_network

let _ = 
  let network = make_network [|28;28;1|] in
  Graph.init network;
  Graph.save network "mnist_cnn.network"
```
Then I got an error: `Exception: Invalid_argument "output_value: functional value"`.  Trying to save a trained network would also yield the same error.

I found that this error message was actually generated by this line in `Owl.Utils.marshal_to_file` function: 
```ocaml
let s = Marshal.to_string x [] 
```
where `x` is a neural network.  I was thinking if this error might be related with the recent update of `Graph` module.  (By the way, `Graph.save_weight` function still works fine.)

**Comment by ryanrhymes** [comment]
Ah, OK, now I see what you meant. Thanks for reporting this. This is not because I changed the implementation to functors. This is simply because `Lambda` neuron contains a function value and cannot be marshalled to a file. In short, you cannot save a network to a file if it contains `lambda` neuron.

There are a couple of solutions for this: 1) you can use zoo to share the model without saving it to a binary file. 2) replace `lambda` with other neurons such as `normalisation` or `mul` neuron.
