### ISSUE TITLE
Docstring for matrix init refers to missing function

### ISSUE THREAD

**Issue by mars0i** [owlbarn/owl#93]
The docstring for `init` in owl_dense_matrix_generic.mli refers to `Owl_utils._index_1d_nd`, but that function doesn't exist in Owl_utils.ml.  I know that there are functions with this name in some of the ndarray source files.  Maybe this part of the docstring isn't needed given that there's `init_nd`? (I was going to fix the docstring and submit a PR, but then wondered if right correction would be to add `_index_1d_nd` to Owl_utils.ml.

**Comment by ryanrhymes** [comment]
Ah, thanks for noticing this. `_index_1d_nd` is actually in `Owl_dense_common`. Yes, please go ahead with PR, and thanks for fixing it 👍

**Comment by mars0i** [comment]
Sorry--there is something I don't understand about Owl, or more likely about OCaml.  How is one supposed to use `Owl_dense_common`?  In utop, it doesn't seem to be contained in what I load with `#require "owl"`.  I'monly able to access `_index_1d_nd` by loading the source file with `#use`.  I fear that there's something obvious that I've forgotten.

**Comment by ryanrhymes** [comment]
Ah, if you check `_oasis` file, you will find `Owl_dense_common` is among InternalModules, which means it won't be installed. That's why you cannot use any function in that module. But I noticed I actually already made an alias and exposed `index_1d_nd` and `index_nd_1d` in `Dense.Ndarray.Generic` module. I will fix the doc shortly.
