### ISSUE TITLE
Question for indexing and slicing tutorial

### ISSUE THREAD

**Issue by mars0i** [owlbarn/owl#98]
I've been reading the indexing and slices tutorial, which is very helpful.  Would it be easy to to add a comment to the tutorial on relative efficiency of slicing as opposed to doing one's own indexing into the original matrix (for example)?

Does slicing copy parts of the matrix into a new data structure, or is it in effect just a convenient way to let Owl manage complex indexing schemes, so that the cost of using slicing would be minimal?  Or maybe slicing is potentially more efficient than indexing by hand because more of the process will stay on the OpenBLAS side?  (I don't know whether that question makes sense.)

(I am thinking about ways to optimize some very slow code, and started looking at slicing as one tool that might help me to restructure it.)

Thanks-

**Comment by ryanrhymes** [comment]
@mars0i  thanks for suggesting this. I can add some tips and discussions about the performance in the tutorial. In case you encounter any performance issues or bugs in using Owl's slicing and indexing functions, please always let me know so I can improve it.

Indexing, slicing, and broadcasting are fundamental functions of the core ndarray module. Currently, taking a slice out (`get_slice`) creates a copy from the original variable; setting a slice (`set_slice`) on the other hand modifies the the original variable directly. In the future, I might consider to introduce `view` into Owl to avoid copying data when slicing data.

The performance of slicing really depends on the actual slice definition, because Owl sticks to the c layout, so slicing at low dimension is always much faster than at high dimension. Owl first calculates the minimum continuous block size then tries to use block copying in CBLAS to speed up the operation. Further optimisation on slicing and broadcasting is on my to-do. As you might have noticed, broadcasting has been significantly optimised these two days (`opt` branch will be merged to master either today or tomorrow).

But yes, please do give it a try to see if slicing can help in improving the performance of your code, and let me know the result. That would be very helpful for me to further improve the slicing function.

**Comment by mars0i** [comment]
> Owl sticks to the c layout, so slicing at low dimension is always much faster than at high dimension. 
I want to make sure that I understand.  For example, with matrices, if I extract a row using `get_slice` (or `get_slice_simple`, that will be faster than if I extract a column, because the internal layout is [row1 row2 ... rowN].  If I extract one column, that means copying *N* blocks of size 1. 

However, with `get_slice`, the copy of the row (or column) that I operate will be made inside OpenBLAS, so the copying itself will be relatively fast.

I'll try out slicing.  Knowing how the underlying layout affects speed will be very helpful.

I had heard of broadcasting but didn't understand what it was.  I just read about it on the web and in Owl's README and tried it out.  Very cool.  I don't think that the project I'm currently working on can make use of broadcasting, but I will look for ways to use it and see if it speeds things up.

**Comment by ryanrhymes** [comment]
Yes, your understanding is correct. The code below: `f` slices a row out whilst `g` slices a column out. On my machine (not very fast), `f` takes about 0.46ms whilst `g` takes 1.82ms

```ocaml
let x = Mat.uniform 1000 1000;;
let f () = Mat.get_slice_simple [[99]; []] x;;
let g () = Mat.get_slice_simple [[]; [99]] x;;
Utils.time f;;
Utils.time g;;
```

But if you mostly operate on matrices, you can just use `Mat.row` and `Mat.col`, they are even fasters. For example, in the code below, `h` does the same thing as `f` and `j` does the same as `g`, but `h` only takes 0.005ms and `j` takes 0.04ms.

```ocaml
let h () = Mat.row x 99;;
let i () = Mat.col x 99;;
Utils.time h;;
Utils.time i;;
```

But note, `Mat.row` does not make a copy of data, so if you modify the returned row, the corresponding elements in `x` will also change. 

In general, `slicing` function is meant for more complicated slice definition of ndarray. I hope this is helpful.

**Comment by ryanrhymes** [comment]
For broadcast, [this page](http://www.scipy-lectures.org/intro/numpy/operations.html) seems helpful? It has very simple rules and I have documented in the code [here](https://github.com/ryanrhymes/owl/blob/390ec38d10205123377c5ba38bf8414a4ed4d0e1/lib/owl_dense_ndarray_generic.ml#L311).

It is a quite useful operation, used a lot in Owl's neural network module.

**Comment by mars0i** [comment]
Oh, that difference between `row`/`col` and `get_slice` is very useful.  I had assumed that `get_slice` would be faster, but that makes sense.  I didn't realize that I could set the underlying array using `row` or `col`.  That actually might be very useful to me, although I can see that it could be dangerous.

Yes, thanks for the broadcast info link. That expands my understanding.
